## Numpy 개요
Numeric + Python = Numpy   
수학 및 과학 연산을 위한 파이썬 패키지   
배열이나 행렬 계산에 용이한 메서드를 제공   
한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함   
관련 사이트 : http://www.numpy.org   
일반 List에 비해 빠르고, 메모리 효율적   

반복문 없이 데이터 배열에 대한 처리를 지원함   
선형대수와 관련된 다양한 기능을 제공함   
Reference Site   
cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy   
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html   
데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS   

## 설치 및 임포트
넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
pip install numpy

In [3]:
import numpy as np
np.__version__

'1.26.4'

## ndim(dimention, rank)
몇 차원인지 반환

In [4]:
a = np.array(0)
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [5]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [6]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [7]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [8]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [11]:
a.shape #2행 3열이 두개가 있어

(2, 2, 3)

In [10]:
a.shape?

Type:        tuple
String form: (2, 2, 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

## shape
행렬의 차원으로, 몇행 몇열인지 반환

In [13]:
a = np.array(3)
a, a.shape # 행렬아니라서 a.shape이 안나옴

(array(3), ())

In [15]:
#1차원 벡터
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [17]:
#2차원 matrix
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [18]:
#3차원 
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## 넘파이 배열
리스트를 넘파이 배열로 생성 np.array(리스트)   
관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [19]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [20]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [21]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [23]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )
# 사이즈는 요소의 개수, 길이는 행의 갯수

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [24]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [25]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
-
배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wis)    <br>   )-
넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차    <br>     -등
리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만   <br>           가능

In [26]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [27]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [29]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype
https://numpy.org/doc/stable/reference/arrays.dtypes.htm    l
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니    다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한    다.
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문 뜻한다.   숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.     뜻한다

In [30]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [33]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환 -> 수용할 수 있는 가장 큰 형식으로 통일시켜
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [32]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.     
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.     
0을 0으로 나누려고 시도하면 np.nan이 나온다.     

In [35]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
# 원래 자료형에서는 0은 에러날텐데 여기는 무한으로 표시해줌

C:\Users\USER\AppData\Local\Temp\ipykernel_19272\3118512324.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\USER\AppData\Local\Temp\ipykernel_19272\3118512324.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [36]:
np.log(0)

C:\Users\USER\AppData\Local\Temp\ipykernel_19272\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [37]:
np.exp(-np.inf)

0.0

## 기술통계

In [38]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [39]:
x.mean()

4.8076923076923075

In [40]:
np.mean(x)  # 평균

4.8076923076923075

In [41]:
np.var(x)  # 분산

115.23224852071006

In [43]:
np.std(x)  # 표준 편차

10.734628476137871

In [42]:
np.max(x)  # 최댓값

23

In [44]:
np.min(x)  # 최소값

-24

In [45]:
np.median(x)  # 중앙값

5.0

## 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.    
각각 1사분위수, 2사분위수, 3사분위수라고 한다.    
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.    

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.    

In [46]:
np.percentile(x, 0)  # 최소값

-24.0

In [47]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [48]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [49]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [50]:
np.percentile(x, 100)  # 최댓값

23.0

## 넘파이 함수로 배열 만들기
np.ones(n) , np.ones((x, y))    
np.zeros(n) , np.zeros((x, y))    
np.empty(n) , np.empty((x, y))    
np.aranges(start, end step)    

reshape(x, y) # 차원 확대    
flatten(x, y) # 차원 축소    

In [55]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 
#ones를 쓰는 건 값 유지를 위함

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [52]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [53]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [54]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [ ]:
# 0으로 메모리 초기화
print(np.zeros(10), np.zeros(10).dtype)

In [ ]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

In [56]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [57]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [58]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [59]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [60]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [61]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [62]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000002152F2AE8E0>
File:            c:\users\user\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end va

In [ ]:
np.logspace?

In [63]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며      ,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [64]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [65]:
arr, arr.ndim, arr.shape


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [66]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [67]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [68]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [69]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [71]:
print(np.arange(2,101,2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [72]:
np.arange(1, 31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [73]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [80]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr5 = np.arange(1, 21).reshape(5, 4)
arr5, arr5.ndim, arr5.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 2,
 (5, 4))

In [81]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [82]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [83]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [84]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

## 넘파이배열의 자료형 형변환   
배열명2 = 배열명1.astype(자료형     <br>  )
자료형 = np.float64, np.int   32

In [87]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [85]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [90]:
matrix.astype('<U5')

NameError: name 'matrix' is not defined

In [89]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [91]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [92]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [93]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [94]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [95]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

## 넘파이 배열의 인덱싱
넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

### 1D array

In [105]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [97]:
a[0]

1

In [98]:
a[[0, 2, 4]]

array([1, 5, 9])

In [99]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] )
b

array([[1, 3],
       [4, 2]])

In [100]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [101]:
a[2] = 0
a

array([1, 3, 0, 7, 9])

In [102]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [103]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

### 2D array

In [107]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [108]:
# 2차원 인덱싱할 때, 값을 하나면 넣으면 행인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [109]:
a[1]

array([5, 6, 7, 8, 9])

In [110]:
a[2]

array([10, 11, 12, 13, 14])

In [111]:
a[-1]

array([10, 11, 12, 13, 14])

In [112]:
a[-2]

array([5, 6, 7, 8, 9])

In [113]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
# 값이 2개 들어가면, 행/열 인덱싱
a[0, 0]

0

In [115]:
a[0, 1]

1

In [116]:
a[0, 2]

2

In [118]:
a[1, 3]

8

In [119]:
a[2, 4]

14

In [120]:
a[-1, -1]

14

In [122]:
# 값 변경
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [123]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [124]:
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [125]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [126]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [127]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

## 넘파이배열 슬라이싱
1차원
넘파이배열[:end] <br>
넘파이배열[start:] <br>
넘파이배열[start:end] <br>
넘파이배열[start:end:step] <br>

2차원 <br>
 
넘파이배열[행, 열] = [start:end:step, start2:end2:step2] <br>

### 1D array

In [129]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [130]:
a[:]

array([1, 3, 5, 7, 9])

In [131]:
 a[1:]

array([3, 5, 7, 9])

In [132]:
a[-1:]

array([9])

In [133]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a[::2]

array([0, 2, 4, 6, 8])

In [135]:
a[1::2]

array([1, 3, 5, 7, 9])

In [136]:
# 거꾸로 나열해보기
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 2D array

In [1]:
import numpy as np

In [2]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [138]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [139]:
a[:-3]

array([], shape=(0, 5), dtype=int32)

In [140]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [141]:
a[:-1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [142]:
a[:, :] # 행의 범위, 열의 범위 -> 콤마로 구분

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [146]:
a[:, -1]

array([14, 19, 24])

In [148]:
a[1:, 2:3]

array([[17],
       [22]])

In [151]:
a[:2, 1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [153]:
a[1,2]

17

In [4]:
# 행 뒤집기
a[::-1]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [5]:
# 열 뒤집기
a[::, ::-1]

array([[14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

## 전치행렬

In [6]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [8]:
# reshape과 transpose은 값이 다름을 유의 -> reshape는 flatten이 선행됨.
print(matrix_d.reshape(2,3)) 

[[1 2 3]
 [4 5 6]]


## 난수로 구성된 넘파이 배열
np.random.randint(start, end, n) : 정수 난  <br> 수
np.random.randint(start, end, (i, j))

In [9]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([9, 3, 6, 2, 5, 3, 5, 2, 1, 9])

In [10]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[4, 7, 5, 5, 4],
       [1, 3, 6, 9, 7]])

## 섞기
np.random.shuffle(넘파이배열) 원본에 바로 적용

In [11]:
np.random.shuffle?

Docstring:
shuffle(x)

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

.. note::
    New code should use the `~numpy.random.Generator.shuffle`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

See Also
--------
random.Generator.shuffle: which should be used for new code.

Examples
--------
>>> arr = np.arange(10)
>>> np.random.shuffle(arr)
>>> arr
[1 7 5 2 9 4 3 6 0 8] # random

Multi-dimensional arrays are only shuffled along the first axis:

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.shuffle(arr)
>>> arr
array([[3, 4, 5], # random
       [6, 7, 8],
       [0, 1, 2]])
Type:      builtin_function_or_method

In [12]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.random.shuffle(matrix_e)
matrix_e

array([ 6,  8,  7,  2,  5,  3,  4,  9, 10,  1])

Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [15]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

array([26, 32, 31, 22, 18, 15])

## 실수 난수
np.random.randn(n) np.random.randn(i, j)

In [16]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([ 1.19529186,  1.70984194,  0.26029129, -0.07810976, -0.15669581,
       -0.23826606, -0.20183461, -1.06231445, -0.51525557, -2.63022511])

In [17]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-1.26066525,  0.49773982, -0.17112138,  0.14285677],
       [ 0.01462168, -1.24657484,  0.69213093, -0.04357935],
       [ 0.98886075,  0.58147308,  0.74632379,  1.1588508 ],
       [-0.74390989,  0.83212453, -0.97801747, -1.62509638]])

In [18]:
matrix1.max(), matrix1.min()

(1.7098419417195934, -2.6302251148458238)

## 집계함수에서의 축
2차원에서의 집계합수(sum, mean   
axis = 0,    1
np.sum(넘파이배열, axis=0      /1)
np.mean(넘파이배열, axis=      0/1)
np.sort(넘파이배열, axis    =0/1)

In [26]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[27,  2, 10,  6, 33],
       [10, 37, 21, 23, 40],
       [26, 11, 41,  3,  4],
       [44, 12, 38, 26, 21],
       [ 1, 15, 17, 32,  9]])

In [21]:
np.sum(m1, axis=0) # (x)행 합계 -> 강사님 표현으로는 열 합계 = 행 방향 합계 라고 정의하는 게 낫다

array([141,  68, 157,  80, 154])

In [22]:
np.sum(m1, axis=1) # 열(y) 합계 -> 마찬가지로 이게 행합계 = 열 방향 합계

array([ 82, 111, 150, 102, 155])

In [23]:
# 1번째행의 합계는
m1[0,:]

array([16,  6, 29, 21, 10])

In [24]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

82

In [28]:
#3번째열의 합계는
np.sum(m1[:,2], axis=0)

127

## np.sort()

In [29]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[12, 44,  1],
       [33, 10, 42],
       [11, 40, 46],
       [20,  5, 25]])

In [30]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x00000119FF64ED40>
File:            c:\users\user\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of 

In [32]:
np.sort(m2) # 행안에서 열정렬 #dafault axis = -1

array([[ 1, 12, 44],
       [10, 33, 42],
       [11, 40, 46],
       [ 5, 20, 25]])

In [33]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[11,  5,  1],
       [12, 10, 25],
       [20, 40, 42],
       [33, 44, 46]])

In [34]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다 (요소별 정렬까지 해주기 때문에)

array([[20,  5, 25],
       [11, 40, 46],
       [33, 10, 42],
       [12, 44,  1]])

In [35]:
np.sort(m2, axis=1) # 열방향 오름차순

array([[ 1, 12, 44],
       [10, 33, 42],
       [11, 40, 46],
       [ 5, 20, 25]])

In [36]:
m2[::-1, ::-1] 

array([[25,  5, 20],
       [46, 40, 11],
       [42, 10, 33],
       [ 1, 44, 12]])

## 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [38]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [39]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

## 넘파이 배열 요소 추가와 삭제
삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
삭제

np.delete(배열명, 위치인덱스, axis=0/1)

In [41]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [43]:
m3[0]

1

In [44]:
m3[-1]

10

In [45]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [46]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [47]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [49]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [50]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [51]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [52]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [53]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [54]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

## 배열 합치기
- np.vstack((배열1,배열2....)) : 세로 합치기
- np.hstack((배열1,배열2....)) : 가로 합치기
- np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [57]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [59]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [60]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [61]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [62]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

## boolean indexing, mask
- 조건절의 결과는 True, False로 반환
- True인 결과의 데이터 반환
- 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [64]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [66]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [82]:
num = np.random.randint(1, 100, 30)
(num > 30) & (num < 70)

array([ True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,
        True, False, False, False, False, False,  True, False, False,
       False,  True,  True])

In [83]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([77, 28, 31, 21,  6, 85, 86, 73, 67, 88, 47,  2,  2, 34, 30, 39, 38,
        94, 26, 63, 11, 30, 56, 71, 47, 49, 42, 37,  2, 81]),
 array([31, 67, 47, 34, 39, 38, 63, 56, 47, 49, 42, 37]))

In [87]:
## 10보다 작거나 90보다 큰 수 출력하기
num = np.random.randint(1,100,30)
num, num[(num > 90) | (num < 10)]

(array([51, 38, 33, 69, 97,  7, 19, 42, 12, 43, 26, 42, 54, 69, 55, 85, 54,
         7, 56, 12, 66, 69, 16, 57, 85, 61, 57, 20, 74, 63]),
 array([97,  7,  7]))

## indexing(filtering)
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

넘파이배열1[넘파이배열2]   
넘파이배열2 : 인덱스 역할 (only 정수형)

In [88]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([31, 35, 68, 69, 32, 64, 93, 42, 85, 80, 71, 95, 75, 40, 95, 78, 10,
        70, 89, 26, 67, 71, 17, 58, 16, 90, 42, 16, 94, 39]),
 array([31, 68, 69, 71, 67]))

## np.where()를 이용한 필터링
np.where(조건식) : 조건식 만족하는 인덱스 반환   
np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값   
배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [90]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [91]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))